/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5bdnbjiRCEQ
 */
import Link from "next/link"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Home() {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <header className="px-4 sm:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <UserIcon className="h-6 w-6" />
          <span className="sr-only">Personal Site</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6 hidden sm:flex">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Experience
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Blog
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
        <div className="sm:hidden flex items-center">
          <button className="p-2 rounded-md hover:bg-gray-300">
            <MenuIcon className="h-6 w-6" />
          </button>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32" id="about">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">About Me</h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Here is a brief introduction about me. I am a software engineer with a passion for coding.
                </p>
              </div>
              <div>
                <img
                  alt="Placeholder for my photo"
                  className="rounded-full"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl lg:text-6xl">My Experience</h2>
                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Here are some of the experiences I've had in my career.
                </p>
              </div>
              <div className="space-y-4">
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Company 1</h3>
                  <p className="text-gray-500">Hiring Dates: 2018 - 2021</p>
                  <p className="text-gray-500">
                    Job Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt, mauris
                    nec fermentum.
                  </p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Company 2</h3>
                  <p className="text-gray-500">Hiring Dates: 2015 - 2018</p>
                  <p className="text-gray-500">
                    Job Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt, mauris
                    nec fermentum.
                  </p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Company 3</h3>
                  <p className="text-gray-500">Hiring Dates: 2012 - 2015</p>
                  <p className="text-gray-500">
                    Job Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt, mauris
                    nec fermentum.
                  </p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Company 4</h3>
                  <p className="text-gray-500">Hiring Dates: Placeholder</p>
                  <p className="text-gray-500">Job Description: Placeholder</p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Company 5</h3>
                  <p className="text-gray-500">Hiring Dates: Placeholder</p>
                  <p className="text-gray-500">Job Description: Placeholder</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">My Blog</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Here are some of my recent blog posts.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
              <Card className="rounded-md shadow-md">
                <CardHeader className="font-bold">Blog Post 1</CardHeader>
                <CardContent className="text-gray-500">This is a summary of blog post 1.</CardContent>
              </Card>
              <Card className="rounded-md shadow-md">
                <CardHeader className="font-bold">Blog Post 2</CardHeader>
                <CardContent className="text-gray-500">This is a summary of blog post 2.</CardContent>
              </Card>
              <Card className="rounded-md shadow-md">
                <CardHeader className="font-bold">Blog Post 3</CardHeader>
                <CardContent className="text-gray-500">This is a summary of blog post 3.</CardContent>
              </Card>
              <Card className="rounded-md shadow-md">
                <CardHeader className="font-bold">Blog Post 4</CardHeader>
                <CardContent className="text-gray-500">This is a summary of blog post 4.</CardContent>
              </Card>
              <Card className="rounded-md shadow-md">
                <CardHeader className="font-bold">Blog Post 5</CardHeader>
                <CardContent className="text-gray-500">This is a summary of blog post 5.</CardContent>
              </Card>
            </div>
            <div className="mt-4">
              <Button variant="link">See more</Button>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-4xl font-bold tracking-tighter md:text-5xl/tight">Contact Me</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                If you have any questions or would like to get in touch, please reach out.
              </p>
            </div>
            <div className="flex space-x-4 justify-center flex-wrap">
              <Button className="inline-flex items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300 mb-2 sm:mb-0">
                <MailboxIcon className="w-4 h-4 mr-2" />
                Email
              </Button>
              <Button className="inline-flex items-center justify-center rounded-md bg-blue-600 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-blue-700/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-blue-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-blue-600 dark:text-gray-50 dark:hover:bg-blue-700 dark:focus-visible:ring-blue-700 mb-2 sm:mb-0">
                <LinkedinIcon className="w-4 h-4 mr-2" />
                LinkedIn
              </Button>
              <Button className="inline-flex items-center justify-center rounded-md bg-black px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-900 dark:text-gray-50 dark:hover:bg-gray-900 dark:focus-visible:ring-gray-900">
                <GithubIcon className="w-4 h-4 mr-2" />
                GitHub
              </Button>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© My Personal Site. All rights reserved.</p>
      </footer>
    </div>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailboxIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
